name: Build and Test the LwM2M registry crate

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build_and_test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        rust_version: ["stable", "nightly", "1.81"]

    steps:
      - name: Checkout code including full history and submodules
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          rustup update
          rustup install ${{ matrix.rust_version }}
          rustup default ${{ matrix.rust_version }}

      - name: Build
        run: |
          cargo --version
          rustc --version
          cargo build --verbose
        working-directory: .

      - name: Test
        run: |
          cargo --version
          cargo test --verbose
        working-directory: .

      - name: Clippy
        run: |
          cargo clippy --version
          cargo clippy --all-targets --all-features -- -D warnings
        working-directory: .

      - name: rustfmt
        run: |
          cargo fmt --version
          cargo fmt --all -- --check
        working-directory: .

      - name: pre-commit
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install pre-commit==4.0.1
          pre-commit run --all-files
        working-directory: .
